/*
Cleemy Expenses

Welcome on the documentation for the CleemyExpenses API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  ExpenseClaimsApi,
  ExpensesApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { LuccaCleemyExpensesCustom } from "./client-custom";

export class LuccaCleemyExpenses extends LuccaCleemyExpensesCustom {
  readonly expenseClaims: ExpenseClaimsApi;
  readonly expenses: ExpensesApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.expenseClaims = new ExpenseClaimsApi(configuration);
    this.expenses = new ExpensesApi(configuration);
  }

}
