/*
Cleemy Expenses

Welcome on the documentation for the CleemyExpenses API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * State of the approval of the expenseClaim. - 0: the approval is created. - 1: the expenseClaim has been partially approved. - 2: the expenseClaim has been approved. - 3: the expenseClaim has been refused. - 4: the expenseClaim has been cancelled.
 * @export
 * @interface ApprovalStateId
 */
export interface ApprovalStateId {
    /**
     * 
     * @type {number}
     * @memberof ApprovalStateId
     */
    'id'?: ApprovalStateIdIdEnum;
}

type ApprovalStateIdIdEnum = 0 | 1 | 2 | 3 | 4


