/*
Cleemy Expenses

Welcome on the documentation for the CleemyExpenses API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Currency
 */
export interface Currency {
    /**
     * ISO code of the currency (eg: \'EUR\', \'USD\', \'GBP\', ...).
     * @type {string}
     * @memberof Currency
     */
    'id'?: string;
    /**
     * Label of the currency (eg: Pound sterling).
     * @type {string}
     * @memberof Currency
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Currency
     */
    'url'?: string;
}

