/*
Cleemy Expenses

Welcome on the documentation for the CleemyExpenses API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Enum } from './enum';
import { ExpenseReceipt } from './expense-receipt';
import { ExpenseTempItemAttendees } from './expense-temp-item-attendees';
import { ExpenseTempItemAuthorizedActions } from './expense-temp-item-authorized-actions';
import { ExpenseTempItemCustomFieldsValue } from './expense-temp-item-custom-fields-value';
import { ExpenseTempItemMileage } from './expense-temp-item-mileage';
import { ExpenseTempItemOriginalTransaction } from './expense-temp-item-original-transaction';
import { ExpenseTempItemProcessedAmounts } from './expense-temp-item-processed-amounts';
import { PaymentMethodId } from './payment-method-id';
import { SourceId } from './source-id';
import { StatusId } from './status-id';

/**
 * The `ExpenseTempItem`, or \"temporary expense\" is an expense that has not yet been declared (within an expense report) by its owner (the user who made the expense).
 * @export
 * @interface ExpenseTempItem
 */
export interface ExpenseTempItem {
    /**
     * 
     * @type {number}
     * @memberof ExpenseTempItem
     */
    'id'?: number;
    /**
     * Day the expense was made.
     * @type {string}
     * @memberof ExpenseTempItem
     */
    'purchasedOn': string;
    /**
     * 
     * @type {ExpenseTempItemOriginalTransaction}
     * @memberof ExpenseTempItem
     */
    'originalTransaction'?: ExpenseTempItemOriginalTransaction;
    /**
     * 
     * @type {ExpenseTempItemProcessedAmounts}
     * @memberof ExpenseTempItem
     */
    'processedAmounts'?: ExpenseTempItemProcessedAmounts;
    /**
     * Nature of the expense: Meals, Train, Taxi, Hotels, Taxi, Mileage... List depends on the app configuration.
     * @type {number}
     * @memberof ExpenseTempItem
     */
    'expenseNatureId': number;
    /**
     * 
     * @type {ExpenseTempItemMileage}
     * @memberof ExpenseTempItem
     */
    'mileage'?: ExpenseTempItemMileage;
    /**
     * The quantity when the expense type is \'Quantity\'.
     * @type {number}
     * @memberof ExpenseTempItem
     */
    'quantity'?: number;
    /**
     * Calculated quantity when the expense type is \'Quantity\' or \'Invitations\' (number of attendees).
     * @type {number}
     * @memberof ExpenseTempItem
     */
    'effectiveQuantity'?: number;
    /**
     * 
     * @type {ExpenseTempItemAttendees}
     * @memberof ExpenseTempItem
     */
    'attendees'?: ExpenseTempItemAttendees;
    /**
     * Axis sections values.
     * @type {Array<any>}
     * @memberof ExpenseTempItem
     */
    'axisSections'?: Array<any>;
    /**
     * Values for custom fields.
     * @type {{ [key: string]: ExpenseTempItemCustomFieldsValue; }}
     * @memberof ExpenseTempItem
     */
    'customFields'?: { [key: string]: ExpenseTempItemCustomFieldsValue; };
    /**
     * Merchant of the expense.
     * @type {any}
     * @memberof ExpenseTempItem
     */
    'merchant'?: any;
    /**
     * 
     * @type {any}
     * @memberof ExpenseTempItem
     */
    'comment'?: any;
    /**
     * The original receipt (PDF file, image, ...).
     * @type {Array<ExpenseReceipt>}
     * @memberof ExpenseTempItem
     */
    'expenseReceipts'?: Array<ExpenseReceipt>;
    /**
     * 
     * @type {ExpenseTempItemAuthorizedActions}
     * @memberof ExpenseTempItem
     */
    'authorizedActions'?: ExpenseTempItemAuthorizedActions;
    /**
     * 
     * @type {SourceId}
     * @memberof ExpenseTempItem
     */
    'sourceId'?: SourceId;
    /**
     * 
     * @type {Enum}
     * @memberof ExpenseTempItem
     */
    'source'?: Enum;
    /**
     * Unique identifier of the user that made this expense.
     * @type {number}
     * @memberof ExpenseTempItem
     */
    'ownerId'?: number;
    /**
     * 
     * @type {PaymentMethodId}
     * @memberof ExpenseTempItem
     */
    'paymentMethodId'?: PaymentMethodId;
    /**
     * 
     * @type {Enum}
     * @memberof ExpenseTempItem
     */
    'paymentMethod'?: Enum;
    /**
     * 
     * @type {StatusId}
     * @memberof ExpenseTempItem
     */
    'statusId'?: StatusId;
    /**
     * 
     * @type {Enum}
     * @memberof ExpenseTempItem
     */
    'status'?: Enum;
}

