/*
Cleemy Expenses

Welcome on the documentation for the CleemyExpenses API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ExpenseTempItemAttendeesExternalInner } from './expense-temp-item-attendees-external-inner';

/**
 * Additional information when the expense type is \'Invitation\'.
 * @export
 * @interface ExpenseTempItemAttendees
 */
export interface ExpenseTempItemAttendees {
    /**
     * Attendees who work for the company (ie: Users in the system).
     * @type {Array<any>}
     * @memberof ExpenseTempItemAttendees
     */
    'internal'?: Array<any>;
    /**
     * External attendees (eg: clients, candidates).
     * @type {Array<ExpenseTempItemAttendeesExternalInner>}
     * @memberof ExpenseTempItemAttendees
     */
    'external'?: Array<ExpenseTempItemAttendeesExternalInner>;
}

