/*
Cleemy Expenses

Welcome on the documentation for the CleemyExpenses API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ExpensesListTempItemsResponseData } from './expenses-list-temp-items-response-data';

/**
 * 
 * @export
 * @interface ExpensesListTempItemsResponse
 */
export interface ExpensesListTempItemsResponse {
    /**
     * 
     * @type {ExpensesListTempItemsResponseData}
     * @memberof ExpensesListTempItemsResponse
     */
    'data'?: ExpensesListTempItemsResponseData;
}

