/*
Cleemy Expenses

Welcome on the documentation for the CleemyExpenses API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Id of the custom field.
 * @export
 * @interface ExpenseTempItemAttendeesExternalInner
 */
export interface ExpenseTempItemAttendeesExternalInner {
    /**
     * 
     * @type {number}
     * @memberof ExpenseTempItemAttendeesExternalInner
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ExpenseTempItemAttendeesExternalInner
     */
    'displayName'?: string;
}

