/*
Cleemy Expenses

Welcome on the documentation for the CleemyExpenses API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ExpenseClaimsCreateNewExpenseClaimResponseDataInnerCreatedExpenseClaim } from './expense-claims-create-new-expense-claim-response-data-inner-created-expense-claim';

/**
 * 
 * @export
 * @interface ExpenseClaimsCreateNewExpenseClaimResponseDataInner
 */
export interface ExpenseClaimsCreateNewExpenseClaimResponseDataInner {
    /**
     * 
     * @type {ExpenseClaimsCreateNewExpenseClaimResponseDataInnerCreatedExpenseClaim}
     * @memberof ExpenseClaimsCreateNewExpenseClaimResponseDataInner
     */
    'createdExpenseClaim'?: ExpenseClaimsCreateNewExpenseClaimResponseDataInnerCreatedExpenseClaim;
}

