/*
Cleemy Expenses

Welcome on the documentation for the CleemyExpenses API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Authorized actions on the expense for the current user.
 * @export
 * @interface ExpenseTempItemAuthorizedActions
 */
export interface ExpenseTempItemAuthorizedActions {
    /**
     * Expense can be deleted by the current authenticated user.
     * @type {boolean}
     * @memberof ExpenseTempItemAuthorizedActions
     */
    'isCancellable'?: boolean;
    /**
     * Expense can be edited by the current authenticated user.
     * @type {boolean}
     * @memberof ExpenseTempItemAuthorizedActions
     */
    'isEditable'?: boolean;
}

