/*
Cleemy Expenses

Welcome on the documentation for the CleemyExpenses API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ExpenseTempItemProcessedAmountsVatBasesInnerCountryVatRate } from './expense-temp-item-processed-amounts-vat-bases-inner-country-vat-rate';

/**
 * 
 * @export
 * @interface ExpenseTempItemProcessedAmountsVatBasesInner
 */
export interface ExpenseTempItemProcessedAmountsVatBasesInner {
    /**
     * 
     * @type {number}
     * @memberof ExpenseTempItemProcessedAmountsVatBasesInner
     */
    'countryVatRateId'?: number;
    /**
     * 
     * @type {ExpenseTempItemProcessedAmountsVatBasesInnerCountryVatRate}
     * @memberof ExpenseTempItemProcessedAmountsVatBasesInner
     */
    'countryVatRate'?: ExpenseTempItemProcessedAmountsVatBasesInnerCountryVatRate;
    /**
     * 
     * @type {number}
     * @memberof ExpenseTempItemProcessedAmountsVatBasesInner
     */
    'vatAmount'?: number;
    /**
     * 
     * @type {number}
     * @memberof ExpenseTempItemProcessedAmountsVatBasesInner
     */
    'amountExcludingVat'?: number;
}

