/*
Cleemy Expenses

Welcome on the documentation for the CleemyExpenses API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Additional information when the expense type is mileage.
 * @export
 * @interface ExpenseTempItemMileage
 */
export interface ExpenseTempItemMileage {
    /**
     * Distance where the unit depends on the establishment.
     * @type {number}
     * @memberof ExpenseTempItemMileage
     */
    'distance'?: number;
    /**
     * Tax horsepower of the vehicle.
     * @type {number}
     * @memberof ExpenseTempItemMileage
     */
    'power'?: number;
    /**
     * The collection of waypoints including intermediate waypoints.
     * @type {Array<any>}
     * @memberof ExpenseTempItemMileage
     */
    'waypoints'?: Array<any>;
}

