/*
Cleemy Expenses

Welcome on the documentation for the CleemyExpenses API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ExpenseClaimsCreateNewExpenseClaimRequestInnerExpenseTempItemsInner } from './expense-claims-create-new-expense-claim-request-inner-expense-temp-items-inner';

/**
 * 
 * @export
 * @interface ExpenseClaimsCreateNewExpenseClaimRequestInner
 */
export interface ExpenseClaimsCreateNewExpenseClaimRequestInner {
    /**
     * Human readable name for this ExpenseClaim (eg: \"May 2022\").
     * @type {string}
     * @memberof ExpenseClaimsCreateNewExpenseClaimRequestInner
     */
    'title': string;
    /**
     * List of all temporary expenses identifiers that should be included in this expense claim.
     * @type {Array<ExpenseClaimsCreateNewExpenseClaimRequestInnerExpenseTempItemsInner>}
     * @memberof ExpenseClaimsCreateNewExpenseClaimRequestInner
     */
    'expenseTempItems': Array<ExpenseClaimsCreateNewExpenseClaimRequestInnerExpenseTempItemsInner>;
}

