/*
Cleemy Expenses

Welcome on the documentation for the CleemyExpenses API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * An expense\'s receipt.
 * @export
 * @interface ExpenseReceipt
 */
export interface ExpenseReceipt {
    /**
     * 
     * @type {string}
     * @memberof ExpenseReceipt
     */
    'id'?: string;
}

