/*
Cleemy Expenses

Welcome on the documentation for the CleemyExpenses API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ExpenseClaimsCreateNewExpenseClaimResponseDataInnerCreatedExpenseClaimNextApprover
 */
export interface ExpenseClaimsCreateNewExpenseClaimResponseDataInnerCreatedExpenseClaimNextApprover {
    /**
     * 
     * @type {string}
     * @memberof ExpenseClaimsCreateNewExpenseClaimResponseDataInnerCreatedExpenseClaimNextApprover
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExpenseClaimsCreateNewExpenseClaimResponseDataInnerCreatedExpenseClaimNextApprover
     */
    'lastName'?: string;
}

