/*
Cleemy Expenses

Welcome on the documentation for the CleemyExpenses API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ExpensesListTempItems400Response
 */
export interface ExpensesListTempItems400Response {
    /**
     * HTTP status code.
     * @type {number}
     * @memberof ExpensesListTempItems400Response
     */
    'Status'?: number;
    /**
     * Human readable error message.
     * @type {string}
     * @memberof ExpensesListTempItems400Response
     */
    'Message'?: string;
}

