/*
Cleemy Expenses

Welcome on the documentation for the CleemyExpenses API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Currency } from './currency';
import { ExpenseTempItemProcessedAmountsVatBasesInner } from './expense-temp-item-processed-amounts-vat-bases-inner';

/**
 * Various amounts in the establishment\'s currency.
 * @export
 * @interface ExpenseTempItemProcessedAmounts
 */
export interface ExpenseTempItemProcessedAmounts {
    /**
     * Original transaction amount converted into the establishment\'s currency.
     * @type {number}
     * @memberof ExpenseTempItemProcessedAmounts
     */
    'grossAmount'?: number;
    /**
     * ISO code of the currency (eg: \'EUR\', \'USD\', \'GBP\', ...).
     * @type {string}
     * @memberof ExpenseTempItemProcessedAmounts
     */
    'currencyId'?: string;
    /**
     * 
     * @type {Currency}
     * @memberof ExpenseTempItemProcessedAmounts
     */
    'currency'?: Currency;
    /**
     * The converted amount after the expense policy has been applied.
     * @type {number}
     * @memberof ExpenseTempItemProcessedAmounts
     */
    'netAmount'?: number;
    /**
     * 
     * @type {Array<ExpenseTempItemProcessedAmountsVatBasesInner>}
     * @memberof ExpenseTempItemProcessedAmounts
     */
    'vatBases'?: Array<ExpenseTempItemProcessedAmountsVatBasesInner>;
}

