/*
Cleemy Expenses

Welcome on the documentation for the CleemyExpenses API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ExpenseTempItemCustomFieldsValue
 */
export interface ExpenseTempItemCustomFieldsValue {
    /**
     * Value inputted by the user.
     * @type {string}
     * @memberof ExpenseTempItemCustomFieldsValue
     */
    'code'?: string;
    /**
     * Label corresponding to the input value based on the configuration (eg: \'Yes\' for checkbox).
     * @type {string}
     * @memberof ExpenseTempItemCustomFieldsValue
     */
    'name'?: string;
}

