/*
Cleemy Expenses

Welcome on the documentation for the CleemyExpenses API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Currency } from './currency';

/**
 * Expense amount in original currency.
 * @export
 * @interface ExpenseTempItemOriginalTransaction
 */
export interface ExpenseTempItemOriginalTransaction {
    /**
     * 
     * @type {number}
     * @memberof ExpenseTempItemOriginalTransaction
     */
    'grossAmount'?: number;
    /**
     * ISO code of the currency (eg: \'EUR\', \'USD\', \'GBP\', ...).
     * @type {string}
     * @memberof ExpenseTempItemOriginalTransaction
     */
    'currencyId'?: string;
    /**
     * Whether the expense was made in a different country than the owner establishment\'s.
     * @type {boolean}
     * @memberof ExpenseTempItemOriginalTransaction
     */
    'isExpenseAbroad'?: boolean;
    /**
     * 
     * @type {Currency}
     * @memberof ExpenseTempItemOriginalTransaction
     */
    'currency'?: Currency;
}

