/*
Cleemy Expenses

Welcome on the documentation for the CleemyExpenses API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Applicable VAT rate for this amount.
 * @export
 * @interface ExpenseTempItemProcessedAmountsVatBasesInnerCountryVatRate
 */
export interface ExpenseTempItemProcessedAmountsVatBasesInnerCountryVatRate {
    /**
     * 
     * @type {number}
     * @memberof ExpenseTempItemProcessedAmountsVatBasesInnerCountryVatRate
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ExpenseTempItemProcessedAmountsVatBasesInnerCountryVatRate
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExpenseTempItemProcessedAmountsVatBasesInnerCountryVatRate
     */
    'url'?: string;
}

