/*
Cleemy Expenses

Welcome on the documentation for the CleemyExpenses API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ExpenseTempItem } from './expense-temp-item';

/**
 * 
 * @export
 * @interface ExpensesListTempItemsResponseData
 */
export interface ExpensesListTempItemsResponseData {
    /**
     * 
     * @type {Array<ExpenseTempItem>}
     * @memberof ExpensesListTempItemsResponseData
     */
    'items'?: Array<ExpenseTempItem>;
}

