/*
Cleemy Expenses

Welcome on the documentation for the CleemyExpenses API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Owner
 */
export interface Owner {
    /**
     * 
     * @type {number}
     * @memberof Owner
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Owner
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Owner
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof Owner
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof Owner
     */
    'lastName'?: string;
}

