/*
Cleemy Expenses

Welcome on the documentation for the CleemyExpenses API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * How this expense was made: the owner used his money, an enterprise debit card, or a Cleemy card: - 0: User - 1: CorporateCard - 3: Cleemy Card
 * @export
 * @enum {string}
 */
export type PaymentMethodId = 0 | 1 | 3

