/*
Cleemy Expenses

Welcome on the documentation for the CleemyExpenses API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The source describes how the expense was created: - 0: Legacy - 1: OldImport - 2: ImportByCb - 3: ImportByNature - 4: Anytime - 5: BudgetInsight - 6: Api - 7: Ocr - 8: Reconciliation - 9: InvoiceAggregator - 10: EmailAttachments - 11: FtpStatementImport - 12: CleemyPayment
 * @export
 * @interface SourceId
 */
export interface SourceId {
    /**
     * 
     * @type {string}
     * @memberof SourceId
     */
    'id'?: string;
}

