/*
Cleemy Expenses

Welcome on the documentation for the CleemyExpenses API.


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Status of the expense. - 0: the expense is not valid. - 1: the expense has been completed by the system and review is still pending - 2: the expense has been completed and reviewed and it can be declared.
 * @export
 * @interface StatusId
 */
export interface StatusId {
    /**
     * 
     * @type {number}
     * @memberof StatusId
     */
    'id'?: StatusIdIdEnum;
}

type StatusIdIdEnum = 0 | 1 | 2


